# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZccMSWMLPaHcxSrBgfrt_Aqt7GC_bUn2
"""

import streamlit as st
from pipeline import run_pipeline


st.set_page_config(
    page_title="Basket Analysis Tool",
    layout="centered"
)

st.title("Basket Analysis Tool")

st.write("Upload required files")

projects_zip = st.file_uploader(
    "Upload projects.zip",
    type=["zip"]
)

reference_file = st.file_uploader(
    "Upload Список.xlsx",
    type=["xlsx"]
)

config_file = st.file_uploader(
    "Upload sheet_config.xlsx",
    type=["xlsx"]
)

if st.button("RUN PIPELINE"):

    if not projects_zip:

        st.error("Upload projects.zip")

    elif not reference_file:

        st.error("Upload Список.xlsx")

    elif not config_file:

        st.error("Upload sheet_config.xlsx")

    else:

        with open("projects.zip", "wb") as f:
            f.write(projects_zip.getbuffer())

        with open("Список.xlsx", "wb") as f:
            f.write(reference_file.getbuffer())

        with open("sheet_config.xlsx", "wb") as f:
            f.write(config_file.getbuffer())

        with st.spinner("Processing..."):

            output_zip = run_pipeline(
                "projects.zip",
                "Список.xlsx",
                "sheet_config.xlsx"
            )

        st.success("Done!")

        with open(output_zip, "rb") as f:

            st.download_button(
                "Download Results",
                f,
                file_name="results.zip"
            )