# -*- coding: utf-8 -*-
"""Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s2IeXApKdyZdvK9kgaEIqiX0CNLD6ub4
"""

import pandas as pd
import zipfile
import shutil
import os

from pathlib import Path
from openpyxl import load_workbook
from openpyxl.styles import Font, Alignment, PatternFill


# =========================
# PROCESS SHEET
# =========================

def process_sheet(df, valid_values):

    df = df.iloc[:, [1,2,7,8,15,16,17]].copy()

    df.columns = list("ABCDEFG")

    mask = (df["A"] == "        ALL VALUES") & (df["B"] != 0)

    df.loc[mask, "A"] = df.loc[mask, "B"]

    df = df.drop(columns=["B"])

    df.columns = list("ABCDEF")

    df = df[["A","D","E","F","B","C"]]

    df.insert(3, "Trips (000)", "")

    df["filter"] = df["A"].astype(str).apply(
        lambda x: 0 if x in valid_values else 1
    )

    df = df[df["A"].astype(str).str.lower() != "    rest"]

    new_columns = [
        "",
        "FMCG trips share",
        "Trips Share",
        "Trips (000)",
        "Affinity index to FMCG",
        "target_trips_raw_CS",
        "target_trips_000_CS",
        "filter"
    ]

    df.columns = new_columns

    return df


# =========================
# FORMAT EXCEL
# =========================

def apply_formatting(output_file):

    wb = load_workbook(output_file)

    fill_gray = PatternFill(
        start_color="777777",
        end_color="777777",
        fill_type="solid"
    )

    fill_light_gray = PatternFill(
        start_color="CCCCCC",
        end_color="CCCCCC",
        fill_type="solid"
    )

    orange_fill = PatternFill(
        start_color="FFA500",
        end_color="FFA500",
        fill_type="solid"
    )

    for sheet_name in wb.sheetnames:

        ws = wb[sheet_name]

        # HEADER
        ws.insert_rows(1)

        ws.merge_cells("B1:E1")

        cell = ws["B1"]

        cell.value = sheet_name

        cell.font = Font(bold=True, size=11)

        cell.alignment = Alignment(
            horizontal="center",
            vertical="center"
        )

        # FORMATTING
        for row in range(3, ws.max_row + 1):

            col_f_value = ws.cell(row=row, column=6).value
            col_h_value = ws.cell(row=row, column=8).value

            if col_h_value == 1:

                try:

                    value_f = float(col_f_value)

                    col_e_value = ws.cell(row=row, column=5).value
                    col_c_value = ws.cell(row=row, column=3).value

                    if value_f > 30 and col_e_value >= 1.5:

                        for col in [2,3,4,5]:

                            ws.cell(row=row, column=col).fill = orange_fill

                        if col_c_value > 0.05:

                            ws.cell(
                                row=row,
                                column=1
                            ).font = Font(bold=True)

                    elif value_f < 15:

                        for col in [2,3,4,5]:

                            ws.cell(row=row, column=col).fill = fill_gray

                        ws.cell(row=row, column=5).value = None

                    elif 15 <= value_f <= 30:

                        for col in [2,3,4,5]:

                            ws.cell(
                                row=row,
                                column=col
                            ).fill = fill_light_gray

                except:
                    pass

        # DELETE ROWS
        for row in range(ws.max_row, 2, -1):

            val = ws.cell(row=row, column=8).value

            if val == 0:

                ws.delete_rows(row)

        # DELETE EXTRA COLUMNS
        if ws.max_column > 5:

            ws.delete_cols(6, ws.max_column - 5)

    wb.save(output_file)


# =========================
# MAIN PIPELINE
# =========================

def run_pipeline(
    projects_zip_path,
    reference_path,
    config_path
):

    # CLEAN
    shutil.rmtree("projects", ignore_errors=True)
    shutil.rmtree("results", ignore_errors=True)

    Path("projects").mkdir(exist_ok=True)
    Path("results").mkdir(exist_ok=True)

    # EXTRACT PROJECTS
    with zipfile.ZipFile(projects_zip_path, 'r') as zip_ref:

        zip_ref.extractall("projects")

    # CONFIG
    config = pd.read_excel(config_path)

    rename_map = dict(
        zip(config["original"], config["rename"])
    )

    order_map = dict(
        zip(config["rename"], config["order"])
    )

    # REFERENCE
    ref_df = pd.read_excel(
        reference_path,
        sheet_name="Список"
    )

    valid_values = set(
        ref_df.iloc[:,0]
        .dropna()
        .astype(str)
    )

    base_path = Path("projects")

    result_path = Path("results")

    # PROCESS PROJECTS
    project_folders = []

    for path in base_path.rglob("*"):

        if path.is_dir():

            excel_files = list(path.glob("*.xlsx"))

            if len(excel_files) > 0:

                project_folders.append(path)

    for project_folder in project_folders:

        if project_folder.is_dir():

            sheets = []

            for file in project_folder.glob("*.xlsx"):

                df = pd.read_excel(file)

                original = file.stem.split("_")[-1]

                sheet_name = rename_map.get(
                    original,
                    original
                )

                order = order_map.get(
                    sheet_name,
                    999
                )

                processed_df = process_sheet(
                    df,
                    valid_values
                )

                sheets.append(
                    (
                        sheet_name,
                        order,
                        processed_df
                    )
                )

            sheets = sorted(
                sheets,
                key=lambda x: x[1]
            )

            output_file = (
                result_path /
                f"Basket Analysis_{project_folder.name}.xlsx"
            )

            with pd.ExcelWriter(
                output_file,
                engine="openpyxl"
            ) as writer:

                for sheet_name, _, df in sheets:

                    df.to_excel(
                        writer,
                        sheet_name=sheet_name,
                        index=False
                    )

            apply_formatting(output_file)

    # ZIP RESULTS
    output_zip = "results.zip"

    with zipfile.ZipFile(
        output_zip,
        'w',
        zipfile.ZIP_DEFLATED
    ) as zipf:

        for file in result_path.glob("*.xlsx"):

            zipf.write(
                file,
                arcname=file.name
            )

    return output_zip